In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
path = "https://dataminingjcomponent.s3.us-east-2.amazonaws.com/prjecte.csv"

In [3]:
dataset = pd.read_csv(path)

In [5]:
dataset['Budget'] = dataset['Budget'].str.replace(',','')
dataset['Gross'] = dataset['Gross'].str.replace(',','')
dataset['Runtime'] = dataset['Runtime'].str.replace('min','')

In [6]:
dataset['Runtime'] = dataset['Runtime'].astype(float)
dataset['Gross'] = dataset['Gross'].astype(float)
dataset['Budget'] = dataset['Budget'].astype(float)

In [7]:
dataset.head()

id  Year  Runtime       Budget        Gross  Ratings  Actors_code  \
0   1  1919    155.0  190000000.0   19235000.0      6.6         1062   
1   2  1922    140.0  720000000.0  844400000.0      6.9          548   
2   3  1929    124.0   95000000.0   65872500.0      7.0           70   
3   4  1929    139.0  193963699.0  308967895.0      7.0           70   
4   5  1930    109.0   35000000.0   11200000.0      6.6           91   

   Dir_code  Prod_code  Story_code  Genre_code  Lang_code Label  
0       765        449         984           4          2   Hit  
1       469        129         531           4          5   Hit  
2        70         33          70          40          2   Hit  
3        70        675          70          40          2   Hit  
4        91         38          91          21          2   Hit

In [9]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 12].values

In [18]:
# Training and testing the model by 70 30 ratio
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30)

In [19]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 50)
classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=50,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [20]:
y_pred = classifier.predict(X_test)

In [21]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, y_pred)
print("Classification Report:",)
print (result1)
result2 = accuracy_score(y_test,y_pred)
print("Accuracy:",result2)

Confusion Matrix:
[[152   0   0]
 [  0 379   0]
 [  0   2  25]]
Classification Report:
              precision    recall  f1-score   support

        Flop       1.00      1.00      1.00       152
         Hit       0.99      1.00      1.00       379
   Super Hit       1.00      0.93      0.96        27

    accuracy                           1.00       558
   macro avg       1.00      0.98      0.99       558
weighted avg       1.00      1.00      1.00       558

Accuracy: 0.996415770609319
